[package]
name = "plabble-codec"
version = "0.1.0"
edition = "2024"
description = "Plabble Transport Protocol codec"
license = "BSD-3-Clause"
categories = ["cryptography", "encoding", "chat", "plabble"]
repository = "https://github.com/plabble/ptp-codec"

[lib]
name = "plabble_codec"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
features = ["ffi"]
path = "src/uniffi-bindgen.rs"

[dependencies]
aes = "0.9.3"
aes-gcm = "0.11.1"
base64 = "0.23.1"
binary-codec = "0.6.7"
# binary-codec = { path = "../Binary-Codec/binary-codec" }
blake2 = "0.11.0"
blake3 = { version = "1.8.7", optional = true }
ctr = "0.10.1"
cipher = "0.5.2"
chacha20 = "0.10.2"
chacha20poly1305 = "0.11.0"
chrono = { version = "0.4.45", features = ["serde"] }
ed25519-dalek = "3.0.0"
ed448-goldilocks = { version = "0.14.0-pre.15", features = ["signing"] }
log = "0.4.34"
toml = { version = "1.1.5", optional = true }
ml-dsa = { version = "0.1.1", optional = true }
ml-kem = { version = "0.3.2", optional = true, features = ["getrandom"] }
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
serde-value = "0.7.0"
serde_json = { version = "1.0.151", optional = true }
serde_with = { version = "3.22.0", features = ["base64", "hex"] }
x25519-dalek = { version = "3.0.0", features = ["static_secrets", "getrandom"] }
poly1305 = "0.9.1"

# WASM dependencies
wasm-bindgen = { version = "0.2.128", optional = true }
js-sys = { version = "0.3.105", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen-futures = { version = "0.4.78", optional = true }
console_log = { version = "1.1.0", optional = true }
getrandom = { version = "0.4.3", optional = true, features = ["wasm_js"] }

# Protocol implementation dependencies
# hints: async-broadcast?
async-channel = { version = "2.5.0", optional = true }

# FFI dependencies
futures = { version = "0.3.34", optional = true }
uniffi = { version = "0.31.0", optional = true }

[features]
default = ["blake-3", "pqc-lite", "pqc-heavy", "blockchain", "ffi", "wasm", "use-toml", "implementation", "protocol", "server", "client"]

# Crypto settings
blake-3 = ["blake3"]
pqc-lite = ["ml-dsa", "ml-kem"]
pqc-heavy = []

# Input/output format
use-json = ["serde_json"]
use-toml = ["toml"]

# Protocol
protocol = ["async-channel"]
server = ["protocol"]
client = ["protocol"]
implementation = []
blockchain = []

# Bindings
wasm = ["wasm-bindgen", "js-sys", "console_error_panic_hook", "console_log", "getrandom", "wasm-bindgen-futures", "client"]
ffi = ["uniffi", "client", "server", "futures"]
unicli = []

[dev-dependencies]
toml = "1.1.5"
hex = "0.4.3"
serde_json = "1.0.151"
env_logger = "0.11.11"

[profile.release]
panic = "abort"
# Tell `rustc` to optimize for small code size.
# s: 676.46 KB z: 638.50 KB
opt-level = "z"
lto = true
